

export const IMAGES = {
    slider1                 : require('../../assets/newDesign/slider1.jpg'),
    slider2                 : require('../../assets/newDesign/slider2.jpg'),
    slider3                 : require('../../assets/newDesign/slider3.jpg'),
    revievedOrders          : require('../../assets/newDesign/revievedOrders.png'),
    loginArrow              : require('../../assets/newDesign/loginArrow.png'),
    addedProducts           : require('../../assets/newDesign/addedProducts.png'),
    revievedMesseges        : require('../../assets/newDesign/revievedMesseges.png'),
    recievedNotifications   : require('../../assets/newDesign/recievedNotifications.png'),
    addProduct              : require('../../assets/newDesign/addProduct.png'),
    favourit                : require('../../assets/newDesign/vision.png'),
    bg                      : require('../../assets/newDesign/bg.png'),
    bg1                     : require('../../assets/newDesign/bg1.png'),
    customer                : require('../../assets/newDesign/customer.png'),
    vendor                  : require('../../assets/newDesign/seller.png'),
    avatar                  : require('../../assets/newDesign/avatar.png'),
    percentage              : require('../../assets/newDesign/percentage.png'),
    downArrow               : require('../../assets/newDesign/downArrow.png'),
    heart                   : require('../../assets/newDesign/heart.png'),
    messege                 : require('../../assets/newDesign/messege.png'),
    eye                     : require('../../assets/newDesign/eye.png'),
    whatsup                 : require('../../assets/newDesign/whatsup.png'),
    facebook                : require('../../assets/newDesign/facebook.png'),
    phone                   : require('../../assets/newDesign/phone.png'),
    dollar                  : require('../../assets/newDesign/dollar.png'),
    send                    : require('../../assets/newDesign/send.png'),
    filter                  : require('../../assets/newDesign/filter.png'),
    trash                   : require('../../assets/newDesign/error.png'),
    bestOffers              : require('../../assets/newDesign/megaphone.png'),
    road                    : require('../../assets/newDesign/road.png'),
    edit2                   : require('../../assets/newDesign/edit2.png'),
    UKflage                 : require('../../assets/newDesign/UKflag.png'),
    Aflage                  : require('../../assets/newDesign/Aflag.jpg'),
    logo                    : require('../../assets/logo.png'),
} 