import LocalizedStrings from "react-native-localization";
export default localization = new LocalizedStrings({
  en: {
    update: "Update",
    noNotification: "No Notifications Exist",
    selectType: "Select Type",
    someThingWentWrong: "some Thing Went Wrong",
    deletedSuccess: "Deleted Successfully",
    addSuccess: "Added Successfully",
    noProductsExist: "No Products Exist",
    fieldRequired: "This Field Is Required",
    discount: "discount",
    cancle: "cancle",
    selectDepartment: "Select Department",
    ProductTitle: "Product Title",
    ProductDetsils: "Product Details",
    SelectProductOnMap: "Select Location On Map",
    AddPhoto: "Add Photo Of Product",
    ProductOffer: "Product Offer",
    ProductPrice: "Product Price",
    SelectCity: "Select City",
    Welcom: "Welcome",
    add: "ADD",
    myProducts: "My Products",
    myMessages: "Messages",
    Mynotifications: "Notifications",
    AddProduct: "Add Product",
    editPassword: "Edit Password",
    editProfile: "Edit Profile",
    profileSettings: "Profile Settings",
    aboutUs: "About Us",
    orderNow: "Order Now",
    location: "Location",
    contactUs: "Contact US",
    categories: "Categories",
    resetFilters: "Reset Filters",
    applyFilters: "Apply Filters",
    allcategories: "All Categories",
    whatyouarsearchfor: "What you are searching for",
    riyal: "AED",
    offers: "offers",
    bestSelle: "best seller",
    favourite: "favourite",
    client: "client",
    seller: "seller",
    orsignInBy: "OR SignIn By",
    noInternetzconnection: "no internet connection",
    travelDate: "Travel Date",
    arrivalDate: "Arrival Date",
    travelDetails: "Travel Details",
    goingComingBack: "Going-coming back",
    going: "Going",
    goingFrom: "Source",
    backTo: "Destination",
    numberOfPersons: "Number of persons",
    specialDicount: "Special Discount",
    Promocode: "Promocode",
    myBooks: "My Books",
    currentBooks: "Currnt Books",
    previousBooks: "Previous Books",
    travelType: "Travel Type",
    sourceDestination: "Source and Destination",
    travelNumber: "Travel Number",
    userName: "username",
    phoneNumber: "phone number",
    messege: "Messege",
    chat: "Chat",
    typeMessege: "type a messege..",
    termsConditions: "Terms and Conditions",
    ordinary: "Ordinary",
    ordinaryDesc: "Standerd bus - without meal",
    classic: "Classic",
    classicDesc: "Special bus - with a meal",
    gold: "Gold",
    excellent: "Excellent bus - Flight",
    goldDesc: "with a special meal",
    bill: "bill",
    date: "Date",
    day: "Day",
    travelCost: "Travel Cost",
    bookNumber: "Book Number",
    payment: "Payment",
    choosePaymentMethod: "Choose Payment Method",
    signIn: "Sign in",
    email: "Email",
    country: "Country",
    city: "City",
    address: "Address",
    password: "Password",
    skipLogin: "Skip Login",
    newMember: "New Member",
    thanks: "Thank You",
    finishBook: "For Finishin your Order",
    willBeContact: "And we will contact you soon",
    forgetPassword: "Forget password?",
    profile: "Profile",
    books: "Books",
    settings: "Settings",
    firstName: "first name",
    lastName: "last name",
    termsConditions: "terms and conditions",
    didYouForgetYourPassword: "forget your password ?",

    /**
     |--------------------------------------------------
     |                 start from here
     |--------------------------------------------------
     */
    home: "Home",
    myAccount: "Account",
    notification: "notification",
    myOrders: "Orders",
    more: "more",
    search: "search",
    login: "Login",
    loginAsDriver: "login as driver",
    allchat: "chats",
    callUs: "Call Us",
    exit: "Exit",
    therisNoChat: "there is no chat",
    send: "Send",
    messege: "message",
    agree: "Agree",
    orderDetail: "order detail",
    addHereOrderDetail: "add order details",
    routeCost: "route coust",
    next: "Next",
    orderHasBeenAdded: "order has been added wating for driver to accept",
    current: "current",
    previous: "previous",
    tripCost: "trip cost",
    thereIsNoNotification: "ther is no notification",
    saveChanges: "save changes",
    facebookAccount: "facebook account",
    sanpchatAccount: "snapchat account",
    twitterAccount: "twitter account",
    instagramAccount: "instagram account",
    pankingTransactions: "panking transactions",
    nearByPlaces: "nearby places",
    expiredOrder: "expired orders",
    newOrder: "new order",
    from: "from",
    to: "to",
    orderCost: "order cost",
    distance: "distance",
    acceptOrder: "accept order",
    rejectOrder: "reject order",
    startChating: "start chatting",
    driverEvaluwate: "evaluate driver",
    youDidnotEvaluwateTheDriver: "you didnot eveluate the driver",
    therIsSomeThingWrong: "ther is some thing wrong",
    pleaseFillAllTheFields: "please fill all the fields",
    didYouForgetYourPassword: "did you forget your password",
    newAccount: "new account",
    register: "register",
    chooseCity: "choose city",
    leaveYourMessage: "leave your message",
    therIsNoTrips: "ther is no trip",
    loginAsClient: "login as client",
    driverHaveAcceptedYourRequest: "driver has accept your request",
    accept: "accept",
    reject: "reject",
    deliveryBill: "deleiveryBill",
    killoMeter: "killo meter",
    completeTherOrder: "complete the order",
    errorLogin: "some thing wrong in email or password",
    thereIsNowPlaces: "ther is no place",
    identityNumber: "identity number",
    vechileNumber: "vechicle number",
    chooseCity: "choose your city",
    setting: "seeting",
    cancelOrder: "cancel order",
    yourAccountHasUpdatedSuccessfully: "your account has updated successfully",
    exportBill: "export bill",
    widthDrawOrder: "withdraw order",
    orderHasDone: "order has done",
    subscribtion: "subscribtion",
    attachTransactionPhoto: "attach transaction photo",
    ForgetPasswordLinkHasBeenSendToYou:
      "forget password link sent to your email",
    YourAccountHasBeenDoneWatingForAdminApproval:
      "your account has been done wating for admin approval",
    watingForAminApproval: "wating for admin approval",
    AddProductIntro:
      "In This Page , You Should Show the Sevices You Wan't to Provide",
    whatsApp: "WhatsApp (with country code)",
    longPressmap: "Press Long On This OR Drag ,Drop On Your Position",

    /*

      Hussein Additions going here

    */
    thisFieldIsRequired:'This Field Is Required',
    registerNewAccount:'Register New Account',
    
    searchText:'what are you searching for....?!',
    descount:'Product Descount',
    whoAreUS : 'Who Are US',
    ourVision: 'Our Vision',
    ourGoals: 'Our Goals',
    rememberMe:'Remember Me',
    createNewAccount:'Don\'t have Account?',
    createOne:'Register Now',
    customer:'Customer',
    vendor:'Vendor',
    lastOffers:'Last Offers',
    searchAllCategories:'Search All Categories',
    english:'English',
    arabic:'عربي',
    logout:'Logout',
    revievedMesseges:'Revieved Messeges',
    recievedNotifications:'Recieved Notifications',
    noAvailableData:'No Available Data',
    personaldata:'Main data',
    changePassword:'Change Password',
    shouldLoginFirst:'you should Login First.',
    pickLocation:'Pick Location',
    Location:"Location",
    passwordmismatch:'Error Password doesn\'t match',
    noProvider: 'sorry you can not chat with the owner of this service',
    drham: 'Drham',
  },
  ar: {
    update: "تحديث",
    noNotification: "لا توجد إشعارات",
    selectType: "اختر النوع",
    someThingWentWrong: "حدث خطأ ما",
    deletedSuccess: "تم الحذف بنجاح",
    addSuccess: "تم الإضافة بنجاح",
    noProductsExist: "لايوجد منتجات",
    fieldRequired: "هذا الحقل مطلوب",
    discount: "الخصم",
    cancle: "إلفاء",
    selectDepartment: "إختر القسم",
    longPressmap: "إضغط مطولا او اسحب واسقط العلامة في موقعك",
    SelectCity: "أختر المدينة",
    ProductTitle: "اسم المنتج",
    ProductDetsils: "تفاصيل المنتج",
    SelectProductOnMap: "أختر موقع الخدمة علي الخريطة",
    AddPhoto: "إضافة صورة للمنتح",
    ProductOffer: "العرض الخاص بالمنتج",
    ProductPrice: "سعر المنتج",
    whatsApp: "واتساب (وكود الدولة)",
    Welcom: "مرحباً بك",
    AddProductIntro: "في هذه الصفحة نرجو منك عرض الخدمة التي تقدمها ٫",
    add: "إضافة",
    myProducts: "منتجاتي",
    myMessages: "رسائلي",
    Mynotifications: "إشعاراتي",
    AddProduct: "إضافة منتج",
    editPassword: "تعديل كلمة المرور",
    editProfile: "تعديل الحساب",
    profileSettings: "إعدادات الحساب",
    aboutUs: "من نحن",
    orderNow: "أطلب الأن",
    location: "الموقع",
    contactUs: "تواصل معنا",
    resetFilters: "الغاء",
    applyFilters: "تصفية المنتجات",
    categories: "الاقسام",
    allcategories: "كل الاقسام",
    bestSelle: "الأكثر مبيعاً",
    offers: "العروض",
    favourite: "المفضلة",
    client: "عميل",
    seller: "بائع",
    home: "الرئيسية",
    myAccount: "حسابى",
    notification: "الاشعارات",
    myOrders: "طلباتى",
    more: "المزيد",
    search: "search",
    login: "تسجيل",
    loginAsDriver: "تسجبل كسائق",
    allchat: "الدردشات",
    callUs: "اتصل بنا",
    termsConditions: "الشروط والاحكام",
    exit: "خروج",
    therisNoChat: "لايوجد اى دردشات",
    send: "ارسال",
    messege: "رسالة",
    agree: "موافق",
    orderDetail: "تقاصيل الطلب",
    addHereOrderDetail: "اضف تفاصيل الطلب",
    routeCost: "تكلفة الطريق",
    next: "التالي",
    orderHasBeenAdded: "تم اضافة الطلب فى انتظار موافقة احد السائقين",
    current: "الحالية",
    previous: "السابقة",
    tripCost: "تكلقة الرحلة",
    thereIsNoNotification: "لايوجد اى اشعارات",
    saveChanges: "حفظ التعديلات",
    facebookAccount: "حساب فيس بوك",
    sanpchatAccount: "حساب سناب شات",
    twitterAccount: "حساب تويتر",
    instagramAccount: "حساب انستجرام",
    pankingTransactions: "العمليات البنكية",
    nearByPlaces: "الاماكن القريبة",
    expiredOrder: "الطلبات المنتهية",
    newOrder: "طلب جديد",
    from: "من",
    to: "الى",
    orderCost: "تكلفة الطلب",
    distance: "المسافة",
    acceptOrder: "قبول الطلب",
    rejectOrder: "رفض الطلب",
    startChating: "ابدا المحادثة",
    driverEvaluwate: "تقييم السائق",
    youDidnotEvaluwateTheDriver: "لم قم بتقييم السائق",
    therIsSomeThingWrong: "هناك خطا ما",
    pleaseFillAllTheFields: "من فضلك قم بملى جميع الحقول",
    didYouForgetYourPassword: "هل نسيت كلمة المرور",
    newAccount: "حساب جديد",
    register: "تسجيل",
    reTypePassword: "اعادة كلمة المرور",
    leaveYourMessage: "اترك رسالتك",
    therIsNoTrips: "لايوجد اى رحلات",
    loginAsClient: "تسجيل كعميل",
    driverHaveAcceptedYourRequest: "تم قبول طلبك من السائق",
    accept: "قبول",
    reject: "رفض",
    deliveryBill: "فاتورة التوصيل",
    killoMeter: "كيلو متر",
    completeTherOrder: "اتمام الطلب",
    errorLogin: "خطا فى بيانات التسجيل",
    thereIsNowPlaces: "لايوجد اى اماكن",
    identityNumber: "رقم الهوية",
    vechileNumber: "رقم المركبة",
    chooseCity: "اختار المدينة",
    setting: "الاعدادات",
    cancelOrder: "الغاء الرحلة",
    yourAccountHasUpdatedSuccessfully: "تم تعديل الحساب بنجاح",
    exportBill: "استخراج فاتورة",
    widthDrawOrder: "تراجع عن الطلب",
    orderHasDone: "تم تنفيذ الطلب",
    subscribtion: "الاشتراكات",
    attachTransactionPhoto: "ارفاق صورة التحويل",
    ForgetPasswordLinkHasBeenSendToYou: "قم بفحص بريدك يمكن استرجاع حسابك هناك",
    YourAccountHasBeenDoneWatingForAdminApproval:
      "تم انشاء الحساب بنجاح فى انتظار موافقه الاداره",
    watingForAminApproval: "فى انتظار موافقه الادارة",

    /**
    |--------------------------------------------------
    |           end here
    |--------------------------------------------------
    */
    noInternetzconnection: "لايوجد اتصال بالانترنت",
    departments: "الاقسام",
    discard: "الغاء",
    rules: "الاسعار تشمل ضريبه القيمه المضاقه",
    pin: "السله",
    completeOrder: "اتمام الطلب",
    products: "منتجات",
    searchFOrMarket: "ابحث عن المتجر",
    orders: "الطلبات",
    travelDate: "تاريخ الذهاب",
    confirmPassword: "تاكيد كلمه المرور",
    arrivalDate: "تاريخ العودة",
    travelDetails: "تفاصيل الرحلة",
    goingComingBack: "ذهاب وعودة",
    going: "ذهاب",
    goingFrom: "قيام من",
    backTo: "وصول الي",
    numberOfPersons: "عدد الافراد",
    specialDicount: "خصم خاص",
    Promocode: "بروموكود",
    myBooks: "حجوزاتي",
    currentBooks: "حجوزاتي الحالية",
    previousBooks: "حجوزاتي السابقة",
    travelType: "نوع الرحلة",
    sourceDestination: "القيام والوصول",
    travelNumber: "رقم الرحلة",
    userName: "اسم المستخدم",
    phoneNumber: "رقم الهاتف",
    chat: "المحادثه",
    typeMessege: "ادخل الرسالة",
    ordinary: "عادية",
    ordinaryDesc: "باص عادي - بدون وجبه",
    classic: "كلاسيك",
    classicDesc: "باص مميز - مع وجبه",
    gold: "ذهبي",
    excellent: "باص فاخر - طيران",
    goldDesc: "مع وجبه مميزه",
    bill: "فاتورة",
    date: "تاريخ",
    day: "اليوم",
    travelCost: "تكلفة الرحلة",
    bookNumber: "رقم الحجز",
    payment: "الدفع",
    choosePaymentMethod: "اختر وسيله للدفع",
    signIn: "دخول",
    email: "البريد الالكتورني",
    country: "الدولة",
    city: "المدينة",
    address: "العنوان",
    password: "كلمة المرور",
    skipLogin: "تخطي التسجيل",
    newMember: "عضو جديد",
    thanks: "نشكركم",
    finishBook: "علي إتمام الحجز",
    willBeContact: "وسيتم التواصل معكم",
    forgetPassword: "استعاده كلمه المرور؟",
    profile: "الشخصية",
    books: "الحجوزات",
    settings: "الأعدادت",
    firstName: "الاسم الاول",
    lastName: "الاسم الاخير",
    orsignInBy: "او سجل الدخول بواسطة",
    riyal: "د.إ",
    whatyouarsearchfor: "ماذا تبحث عن",

    /*

      Hussein Additions going here

    */
    thisFieldIsRequired:'هذا الحقل مطلوب',
    registerNewAccount:'تسجيل حساب جديد',
    
    searchText:'مادا تبحث عن......؟!',
    descount:'نسبة الخصم',
    whoAreUS : 'من نحن',
    ourVision: 'رؤيتنا',
    ourGoals: 'هدفنا',
    rememberMe:'تذكرني',
    createNewAccount:'ليس لديك حساب؟',
    createOne:'تسجيل الان',
    customer:'عميل',
    vendor:'بائع',
    lastOffers:'أخر العروض',
    searchAllCategories:'بحث في جميع الاقسام',
    english:'English',
    arabic:'عربي',
    logout:'تسجيل خروج',
    revievedMesseges:'الرسائل المستلمة',
    recievedNotifications:'الاشعارات المستلمة',
    noAvailableData:'لا يوجد بيانات متوفرة',
    personaldata:'البيانات الاساسية',
    changePassword:'تغيير الرقم السري',
    shouldLoginFirst:'يجب تسجيل الدخول اولا.',
    pickLocation:'اختر الموقع',
    Location:"الموقع",
    passwordmismatch:'كلمة المرور غير مطابقة',
    noProvider: 'اسف, لا يمكنك فتح الدردشة مع صاحب الخدمة.',  
    drham: 'درهم',
  }
});
